project:
  type: website

website:
  title: "Sistemas Agroforestales (SAF)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ZarateUlisess/Sistemas-Agroforestales-SAF-

format:
  html:
    theme: vapor
    css: styles.css



